return {
 "wbthomason/packer.nvim",
 "nvim-lua/plenary.nvim",
 "numToStr/Comment.nvim",
 "JoosepAlviste/nvim-ts-context-commentstring",
 "kyazdani42/nvim-tree.lua",
 "christoomey/vim-tmux-navigator",
 "hrsh7th/nvim-cmp",
 "hrsh7th/cmp-buffer",
 "hrsh7th/cmp-path",
 "saadparwaiz1/cmp_luasnip",
 "hrsh7th/cmp-nvim-lsp",
 "hrsh7th/cmp-nvim-lua",
 "L3MON4D3/LuaSnip",
 "rafamadriz/friendly-snippets",
 "neovim/nvim-lspconfig",
 "williamboman/nvim-lsp-installer",
 "jose-elias-alvarez/null-ls.nvim",
 "nvim-treesitter/nvim-treesitter",
 "ThePrimeagen/harpoon",
 }

